### ISSUE TITLE
Enable coverage compiling and display code coverage badge in README

### ISSUE THREAD

**Issue by yixinglu** [vesoft-inc/nebula#968]
### TODO

- [ ] Add code coverage compiling options
- [ ] Upload result to codecov.io/coveralls.io
- [ ] Add badge in README

### reference

- https://github.com/marketplace/actions/codecov
- https://github.com/codecov/codecov-action
- https://github.com/vesoft-inc/nebula/workflows/Nebula%20Build%20and%20Test%20Workflow/badge.svg
- https://github.com/codecov/example-cpp11-cmake
- https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html
- https://stackoverflow.com/questions/13116488/detailed-guide-on-using-gcov-with-cmake-cdash/46232989#46232989
- https://gcovr.com/en/stable/guide.html
- https://codecov.io/gh
- https://github.com/SimonKagstrom/kcov/issues/242
- https://coveralls.io/
- kcov: https://github.com/SimonKagstrom/kcov/blob/master/doc/coveralls.md
